spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/management
    username: management
    password: management
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:management
#    username: sa
#    password: 
  h2:
    console:
      enabled: true
debug: true
logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        management:
          mapper:
            ShippingMapper: DEBUG
    